### ISSUE TITLE
How to generate maks?

### ISSUE THREAD

**Issue by Shuyun-Wang** [LIUTIGHE/BSCV-Dataset#2]
I have serval test videos (GT videos are available) needs to be recovery, so how can i generate the corresponding mask?
Thx for your reply and time.

**Comment by LIUTIGHE** [comment]
For such testing, if the GT videos are availiable, you can check the section A.1 of our supplementary materials availiable on [OpenReview](https://openreview.net/attachment?id=cF6rQz8V3V&name=supplementary_material). 
The introduced process is used to simulate the inaccurate human indication which may caused some ignorance. You can further revise or draw from scratch using some labelling software for image/video segmentation.

**Comment by Shuyun-Wang** [comment]
> For such testing, if the GT videos are availiable, you can check the section A.1 of our supplementary materials availiable on [OpenReview](https://openreview.net/attachment?id=cF6rQz8V3V&name=supplementary_material). The introduced process is used to simulate the inaccurate human indication which may caused some ignorance. You can further revise or draw from scratch using some labelling software for image/video segmentation.

Thx for your reply, this supplementary really helps me a lot.
